name: Testing stuff

env:
  COMMIT_MESSAGES: ${{ join(github.event.commits.*.message, ',') }}

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: does contain 'skip'
        env:
          TAG_RELEASE_CONDITION: ${{ github.event_name == 'push' && contains(env.COMMIT_MESSAGES, '#skip') == false }}
          CONDITION: ${{ contains(env.COMMIT_MESSAGES, '#skip') == false }}
        run: |
          if ${{ contains(env.COMMIT_MESSAGES, '#skip') == false }}; then
            echo "No '#skip' found in commit messages"
          else
            echo "'#skip' found in commit messages"
          fi
