name: Development pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  TAG_RELEASE_CONDITION: ${{ github.event_name == 'push' && contains(toJson(github.event.commits), '#skip') == false }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Check styles
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Tests
        run: npm run test
      - name: E2E Tests
        run: npm run 'test:e2e'
      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
  tag-release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.env.TAG_RELEASE_CONDITION == true }}
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notification:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          text: A new version of Pokedex deployed
          details: to https://full-stack-open-pokedex-2gli.onrender.com/ by ongThien
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          text: Build failed
          details: commit ${{github.event.commits.*.url}} by ${{ github.event.commits.committer.username }} broke the build
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
